# Einführung in NumPy

In dieser Lektion stellen wir **NumPy** vor – eine leistungsstarke Bibliothek für numerische Berechnungen in Python. Wir werden folgende Themen behandeln:

- Was ist NumPy und warum sollte man es verwenden?
- Installation und Import von NumPy
- Erstellen von NumPy-Arrays und Erkundung ihrer Attribute
- Array-Operationen (Indexierung, Slicing, mathematische Operationen, Broadcasting, Aggregatfunktionen)
- Matrixoperationen (Erstellung, Multiplikation, Transponieren, Umformen)
- Praktische Übungen zur Anwendung dieser Konzepte

## Was ist NumPy und warum sollte man es verwenden?

- **NumPy** steht für *Numerical Python* und ist eine der zentralen Bibliotheken für numerische Berechnungen.
- Es bietet Unterstützung für große, mehrdimensionale Arrays und Matrizen.
- Viele eingebaute mathematische Funktionen ermöglichen eine effiziente Verarbeitung dieser Arrays.

### Vorteile:

- **Leistung:** Array-Operationen sind in C implementiert und daher deutlich schneller als Python-Schleifen.
- **Speichereffizienz:** Arrays sind dicht gepackt und benötigen weniger Speicher als Python-Listen.
- **Funktionalität:** Es gibt viele vektorisierte Operationen und Funktionen für lineare Algebra, Statistik und mehr.

## Installation und Import von NumPy

Falls NumPy noch nicht installiert ist, kannst du es mit `conda` installieren.  
**Stelle sicher, dass du das richtige Conda-Umfeld (Environment) für diesen Kurs aktiviert hast, bevor du die Installation durchführst.**  

Falls du nicht sicher bist, welches Environment aktiv ist, kannst du es mit folgendem Befehl überprüfen:

```
conda info --envs
```

Falls du ein bestimmtes Environment aktivieren musst, ersetze `<env-name>` mit dem Namen des Environments und führe aus:

```
conda activate <env-name>
```

### Installation im Terminal (Anaconda Prompt)
Öffne das Anaconda Prompt (oder ein Terminal) und führe folgenden Befehl aus:

```
conda install numpy -y
```

### Import von NumPy
Nach der Installation kannst du NumPy in deinem Python-Code importieren:

```python
import numpy as np
```

In [ ]:
import numpy as np 
array_one= np.array([[1,2,3,4,6],[6,7,8,9,10]])
#array_two=np.array([[0.11,0.12,0.13,0.14,0.15][0.16,0.17,0.18,0.19,0.20]])

#print(array_one,'\n')
#print(array_two)


#print(array_one[0:])
#print(array_one[:,2])

#print(array_one[:,4])
#print(array_one[:,2])

#print(array_one[1,1])
#print(array_one[0,1:5:2])

array_three= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
#print(array_three,"\n")
#print(array_three[:,1,:])

#array_three[:,0,:]=[100,200],[300,400]
#print(array_three[:,0,:])

array_four=np.zeros(([2,3,3]), dtype='int32')

#print(array_four)

array_w=np.full((3,3),12, dtype='int32' )
#print(array_w,'\n')
#print(array_w[0,:])

array_w= np.full_like(array_three,2)
#print(array_w)

array_w=np.random.randint(10, size=(3,3))

#print(array_w)

#array_n= np.identity(5)
#print(array_n)

#array_eins=([[1,2,3]])
#array_repeat=np.repeat(array_eins,3, axis=0)
#print(array_repeat)





[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [124]:
# Importiere NumPy
import numpy as np

# Erstelle ein grundlegendes NumPy-Array aus einer Python-Liste
array_from_list = np.array([1, 2, 3, 4, 5])
print('Array aus Liste:', array_from_list)



Array aus Liste: [1 2 3 4 5]


## NumPy-Arrays vs. Python-Listen

- **Homogenität:** NumPy-Arrays sind homogen (alle Elemente haben denselben Typ), während Python-Listen gemischte Typen enthalten können.
- **Leistung:** NumPy-Arrays unterstützen vektorisierte Operationen und sind für numerische Aufgaben viel schneller.
- **Speichereffizienz:** Arrays benötigen weniger Speicher als Listen.
- **Funktionalität:** Viele eingebaute mathematische Operationen sind direkt auf NumPy-Arrays anwendbar.

In [4]:
# Vergleich von Python-Listen und NumPy-Arrays
python_list = [1, 2, 3, 4, 5]
numpy_array = np.array([1, 2, 3, 4, 5])

# Multipliziert man eine Python-Liste mit 2, wird die Liste repliziert
print('Python-Liste multipliziert mit 2:', python_list * 2)

# Bei einem NumPy-Array wird jedes Element mit 2 multipliziert
print('NumPy-Array multipliziert mit 2:', numpy_array * 2)

Python-Liste multipliziert mit 2: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
NumPy-Array multipliziert mit 2: [ 2  4  6  8 10]


## Erstellen von NumPy-Arrays

Es gibt verschiedene Möglichkeiten, Arrays in NumPy zu erstellen:

### 1. Verwendung von `np.array`

Konvertiere eine Python-Liste in ein NumPy-Array.

In [ ]:
data = [10, 20, 30, 40, 50]
arr = np.array(data)
print('NumPy-Array:', arr)

### 2. Verwendung von `np.zeros` und `np.ones`

- `np.zeros(shape)` erstellt ein Array, das mit Nullen gefüllt ist.
- `np.ones(shape)` erstellt ein Array, das mit Einsen gefüllt ist.

In [ ]:
# Array mit Nullen: 3 Zeilen x 4 Spalten
nullen_array = np.zeros((3, 4))
print('Nullen-Array:\n', nullen_array)

# Array mit Einsen: 2 Zeilen x 5 Spalten
einsen_array = np.ones((2, 5))
print('Einsen-Array:\n', einsen_array)

Nullen-Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Einsen-Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### 3. Verwendung von `np.arange` und `np.linspace`

- `np.arange(start, stop, step)` erstellt ein Array mit gleichmäßig verteilten Werten.
- `np.linspace(start, stop, num)` erstellt ein Array mit einer festgelegten Anzahl gleichmäßig verteilter Werte.

In [12]:
# Mit np.arange: Werte von 0 bis 8 (Schrittweite 2)
arange_array = np.arange(0, 10, 2)
print('np.arange:', arange_array)

# Mit np.linspace: 5 Werte gleichmäßig verteilt zwischen 0 und 1
linspace_array = np.linspace(0, 1, 5)
print('np.linspace:', linspace_array)

np.arange: [0 2 4 6 8]
np.linspace: [0.   0.25 0.5  0.75 1.  ]


### Übung: Verschiedene Arten von Arrays erstellen (5 Minuten)

Erstelle die folgenden Arrays und gib jeweils ihre Form (`shape`) und den Datentyp (`dtype`) aus:

1. Ein Array aus der Liste `[7, 14, 21, 28]` mittels `np.array`.
2. Ein 2x3 Array, das nur Nullen enthält, mit `np.zeros`.
3. Ein 3x2 Array, das nur Einsen enthält, mit `np.ones`.
4. Ein Array mit Werten von 0 bis 18 (in Schritten von 3) mittels `np.arange`.
5. Ein Array mit 6 Werten, die gleichmäßig zwischen 5 und 10 verteilt sind, mittels `np.linspace`.

In [13]:
# 1. Array aus der Liste
array_liste = np.array([7, 14, 21, 28])
print('Array aus Liste:', array_liste, 'Form:', array_liste.shape, 'dtype:', array_liste.dtype)

# 2. 2x3 Array mit Nullen
array_nullen = np.zeros((2, 3))
print('2x3 Nullen-Array:\n', array_nullen, '\nForm:', array_nullen.shape, 'dtype:', array_nullen.dtype)

# 3. 3x2 Array mit Einsen
array_einsen = np.ones((3, 2))
print('3x2 Einsen-Array:\n', array_einsen, '\nForm:', array_einsen.shape, 'dtype:', array_einsen.dtype)

# 4. Array mit Werten von 0 bis 18 in Schritten von 3
array_arange = np.arange(0, 19, 3)
print('Array mit arange:', array_arange, 'Form:', array_arange.shape, 'dtype:', array_arange.dtype)

# 5. Array mit 6 Werten zwischen 5 und 10
array_linspace = np.linspace(5, 10, 6)
print('Array mit linspace:', array_linspace, 'Form:', array_linspace.shape, 'dtype:', array_linspace.dtype)

Array aus Liste: [ 7 14 21 28] Form: (4,) dtype: int64
2x3 Nullen-Array:
 [[0. 0. 0.]
 [0. 0. 0.]] 
Form: (2, 3) dtype: float64
3x2 Einsen-Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]] 
Form: (3, 2) dtype: float64
Array mit arange: [ 0  3  6  9 12 15 18] Form: (7,) dtype: int64
Array mit linspace: [ 5.  6.  7.  8.  9. 10.] Form: (6,) dtype: float64


## Array-Attribute

Jedes NumPy-Array besitzt mehrere nützliche Attribute:

- **`shape`**: Die Dimensionen des Arrays (Zeilen, Spalten etc.)
- **`dtype`**: Der Datentyp der Elemente
- **`size`**: Gesamtanzahl der Elemente im Array
- **`ndim`**: Anzahl der Dimensionen (Achsen) des Arrays

In [14]:
beispiel_array = np.array([[1, 2.0, 3], [4, 5, 6]])
print('Array:')
print(beispiel_array)

print('Shape:', beispiel_array.shape)
print('Datentyp:', beispiel_array.dtype)
print('Anzahl der Elemente:', beispiel_array.size)
print('Anzahl der Dimensionen:', beispiel_array.ndim)

Array:
[[1. 2. 3.]
 [4. 5. 6.]]
Shape: (2, 3)
Datentyp: float64
Anzahl der Elemente: 6
Anzahl der Dimensionen: 2


### Übung: Umformen und Größenüberprüfung

Erstelle ein 1D-Array mit den Werten von 0 bis 11 (insgesamt 12 Elemente). Forme dieses Array in ein 3x4 Array um und gib dann die Gesamtanzahl der Elemente (`size`) aus, um zu bestätigen, dass diese gleich bleibt.

In [ ]:
array_1d = np.arange(12)
print('1D Array:', array_1d)

array_3x4 = np.reshape(array_1d, (3, 4))
print('3x4 Array:\n', array_3x4)

print('Größe des Arrays:', array_3x4.size)
print('Shape des Arrays:', array_3x4.shape)

1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
3x4 Array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Größe des Arrays: 12
Shape des Arrays: (2, 6)


## Array-Operationen

### Indexierung und Slicing

Auf Elemente eines NumPy-Arrays kann man ähnlich wie bei Python-Listen zugreifen:

- **Indexierung:** Verwende eckige Klammern `[]` mit dem Index (beginnend bei 0), um ein einzelnes Element abzurufen.
- **Slicing:** Verwende den Doppelpunkt `:`, um einen Teil des Arrays auszuwählen.

In [16]:
beispiel_array = np.array([10, 20, 30, 40, 50])

print('beispiel_array: ', beispiel_array)

beispiel_array:  [10 20 30 40 50]


In [17]:
# Indexierung: Hole das dritte Element (Index 2)
print('Drittes Element:', beispiel_array[2])

Drittes Element: 30


In [20]:
# Slicing: Hole Elemente von Index 1 bis 3 (Index 4 wird ausgeschlossen)
print('Slice von Index 1 bis 4:', beispiel_array[1:4])

Slice von Index 1 bis 4: [20 30 40]


In [19]:
print('Jedes zweite Element:', beispiel_array[::2])

Jedes zweite Element: [10 30 50]


In [ ]:
print('Letzte zwei Element:', beispiel_array[-2:])

Letztes Element: [40 50]


In [22]:
indizes = [0, 2, 4]
print('Elemente an Indizes 0, 2, 4:', beispiel_array[indizes])

Elemente an Indizes 0, 2, 4: [10 30 50]


In [25]:
beispiel_array

array([10, 20, 30, 40, 50])

In [29]:
beispiel_array >= 25

array([False, False,  True,  True,  True])

In [30]:
bool_array = np.array([True, False, True, False, True])
print('Elemente mit Booleschem Array:', beispiel_array[bool_array])

Elemente mit Booleschem Array: [10 30 50]


### Übung: Indexierung und Slicing

Erstelle ein 1D-Array mit den Zahlen von 0 bis 19. Extrahiere anschließend:

1. Die ersten 5 Elemente
2. Die letzten 5 Elemente

In [22]:
array_0_19 = np.arange(20)
print('Array von 0 bis 19:', array_0_19)

# Die ersten 5 Elemente
print('Erste 5 Elemente:', array_0_19[:5])

# Die letzten 5 Elemente
print('Letzte 5 Elemente:', array_0_19[-5:])

Array von 0 bis 19: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Erste 5 Elemente: [0 1 2 3 4]
Letzte 5 Elemente: [15 16 17 18 19]


### Mathematische Operationen (Elementweise)

NumPy ermöglicht arithmetische Operationen auf Arrays elementweise.

In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b

print('Addition:', c)
print('Subtraktion:', a - b)
print('Multiplikation:', a * b)
print('Division:', a / b)

Addition: [5 7 9]
Subtraktion: [-3 -3 -3]
Multiplikation: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


### Übung: Elementweise Operationen

Erstelle zwei Arrays `x` und `y` der gleichen Größe (z. B. `[2, 4, 6, 8]` und `[1, 3, 5, 7]`). Führe elementweise Addition, Subtraktion, Multiplikation und Division durch und berechne anschließend den Mittelwert jedes Ergebnisses.

In [26]:
x = np.array([2, 4, 6, 8])
y = np.array([1, 3, 5, 7])

addition = x + y
subtraktion = x - y
multiplikation = x * y
division = x / y

print('Addition:', addition)
print('Subtraktion:', subtraktion)
print('Multiplikation:', multiplikation)
print('Division:', division)

Addition: [ 3  7 11 15]
Subtraktion: [1 1 1 1]
Multiplikation: [ 2 12 30 56]
Division: [2.         1.33333333 1.2        1.14285714]


### Broadcasting

Broadcasting ermöglicht es NumPy, Operationen auf Arrays unterschiedlicher Formen durchzuführen, indem das kleinere Array entlang der fehlenden Dimensionen erweitert wird. Zum Beispiel das Addieren eines Vektors zu jeder Zeile einer Matrix.

In [36]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

vektor = np.array([1, 0, 1])

# Broadcasting: Addiere den Vektor zu jeder Zeile der Matrix
ergebnis = matrix + vektor
print('Matrix:\n', matrix)
print('Vektor:', vektor)
print('Ergebnis der Broadcasting-Addition:\n', ergebnis)

Matrix:
 [[1 2 3]
 [4 5 6]]
Vektor: [1 0 1]
Ergebnis der Broadcasting-Addition:
 [[2 2 4]
 [5 5 7]]


### Erklärung des Ergebnises
  
Da die Matrix die Form `(2,3)` und der Vektor die Form `(3,)` hat, wird der Vektor so behandelt, als hätte er die Form `(1,3)`.  
Anschließend wird er entlang der fehlenden ersten Dimension auf `(2,3)` erweitert und dann elementweise addiert.


### Beispiel

In [43]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

result = a + b
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
print("Shape of result:", result.shape)

print(result)

Shape of a: (3,)
Shape of b: (3, 1)
Shape of result: (3, 3)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


### Erklärung des Ergebnises
 
- `a` hat die Form `(3,)` (ein eindimensionales Array mit 3 Elementen).  
- `b` hat die Form `(3,1)` (eine Spalte mit 3 Zeilen).  

Beim Broadcasting wird `a` so behandelt, als hätte es die Form `(1,3)`,  
damit es mit `b` ( `(3,1)` ) kompatibel wird.  
Dann wird `a` entlang der ersten Dimension auf `(3,3)` erweitert und die Addition erfolgt elementweise.


### Übung: Broadcasting in Aktion

Erstelle ein 3x3 Array, das die Zahlen von 1 bis 9 enthält (aufsteigend zeilenweise). Erstelle außerdem einen Vektor mit 3 Elementen, z. B. `[2, 3, 4]`. Multipliziere das Array elementweise mit diesem Vektor unter Verwendung von Broadcasting und gib das Ergebnis aus.

In [44]:
array_3x3 = np.arange(1, 10).reshape(3, 3)
vektor_3 = np.array([2, 3, 4])

ergebnis_broadcast = array_3x3 * vektor_3
print('3x3 Array:\n', array_3x3)
print('Vektor:', vektor_3)
print('Ergebnis der elementweisen Multiplikation (Broadcasting):\n', ergebnis_broadcast)

3x3 Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vektor: [2 3 4]
Ergebnis der elementweisen Multiplikation (Broadcasting):
 [[ 2  6 12]
 [ 8 15 24]
 [14 24 36]]


### Übung: Einfache numerische Berechnung

Stell dir vor, du hast ein Array, das die zurückgelegten Entfernungen (in Kilometern) verschiedener Fahrzeuge darstellt.

1. Erstelle ein Array mit den folgenden Entfernungen: `[15, 30, 45, 60, 75]`.
2. Wandle diese Entfernungen in **Meilen** um (Umrechnungsfaktor: 1 km = 0.621371 Meilen).
3. Berechne die **Gesamtentfernung** in Meilen.

In [49]:
# Lösung zu Übung
entfernungen_km = np.array([15, 30, 45, 60, 75])
umrechnungsfaktor = 0.621371

# Wandle Entfernungen in Meilen um
entfernungen_meilen = entfernungen_km * umrechnungsfaktor
print('Entfernungen in Meilen:', entfernungen_meilen)

# Berechne die Gesamtentfernung in Meilen
gesamt_entfernung_meilen = np.sum(entfernungen_meilen)
print('Gesamtentfernung in Meilen:', gesamt_entfernung_meilen)

Entfernungen in Meilen: [ 9.320565 18.64113  27.961695 37.28226  46.602825]
Gesamtentfernung in Meilen: 139.808475


### Aggregatfunktionen

NumPy bietet Funktionen, um Werte in einem Array zu aggregieren:

- **`np.sum()`**: Summe aller Elemente
- **`np.mean()`**: Durchschnitt (Mittelwert) der Elemente
- **`np.std()`**: Standardabweichung
- **`np.min()`**: Minimaler Wert
- **`np.max()`**: Maximaler Wert

In [53]:
data = np.array([1, 2, 3, 4, 5])

print('Summe:', np.sum(data))
print('Mittelwert:', np.mean(data))
print('Standardabweichung:', np.std(data))
print('Minimaler Wert:', np.min(data))
print('Maximaler Wert:', np.max(data))

Summe: 15
Mittelwert: 3.0
Standardabweichung: 1.4142135623730951
Minimaler Wert: 1
Maximaler Wert: 5


### Übung: Weitere Aggregatfunktionen

Erstelle ein zufälliges 2D-Array der Größe 4x4 (mit `np.random.randint`, z. B. Werte zwischen 0 und 100). Berechne:

1. Den Median aller Elemente (Tipp: `np.median`)
2. Die Summe der Elemente entlang der Zeilen (axis=1)
3. Die Summe der Elemente entlang der Spalten (axis=0)

In [ ]:
array_3x4 = np.random.randint(0, 101, (3, 4))
print('3x4 Zufalls-Array:\n', array_3x4)

median_wert = np.median(array_3x4)
summe_zeilen = np.sum(array_3x4, axis=1)
summe_spalten = np.sum(array_3x4, axis=0)

print('Median:', median_wert)
print('Summe je Zeile:', summe_zeilen)
print('Summe je Spalte:', summe_spalten)

3x4 Zufalls-Array:
 [[46 68 65 43]
 [46 14 39 93]
 [38 77 66 41]]
Summe von allen Elementen: 636
Summe von Zeilen: [130 159 170 177]
Summe von Spalten: [222 192 222]


In [3]:
def summe(liste: list | np.ndarray) -> float:
    summe = 0
    for element in liste:
        summe += element
    return summe

In [4]:
import random
a_list = [random.randint(0, 1000) for _ in range(10000000)] # Python List
a_array = np.array(a_list) # NumPy Array

In [69]:
%timeit summe(a_list)

322 ms ± 2.93 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit sum(a_list)

61.6 ms ± 409 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
%timeit np.sum(a_array)

3.85 ms ± 68.2 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Übung: Erstelle ein Array und führe Operationen aus

1. Erstelle ein 2D NumPy-Array der Form **(4, 5)** mit zufälligen Ganzzahlen zwischen 0 und 50.
2. Berechne die **Gesamtsumme** aller Elemente im Array.
3. Ermittle den **Mittelwert** jeder Spalte.

In [ ]:
# Lösung zu Übung
array_uebung1 = np.random.randint(0, 51, (4, 5))
print('Übungs-Array:\n', array_uebung1)

gesamt_summe = np.sum(array_uebung1)
print('Gesamtsumme der Elemente:', gesamt_summe)

spalten_mittelwert = np.mean(array_uebung1, axis=0)  # axis=0 berechnet den Mittelwert spaltenweise
print('Mittelwert jeder Spalte:', spalten_mittelwert)

### Übung: Berechne Statistiken für einen Datensatz mit NumPy

Gegeben sei der folgende Datensatz von Prüfungsergebnissen. Berechne:

- Den **Gesamtdurchschnitt** der Noten
- Die **Standardabweichung** der Noten
- Den **höchsten** und **niedrigsten** Wert

Datensatz: `[88, 92, 79, 93, 85, 78, 91, 87, 95, 89]`

In [ ]:
# Lösung zu Übung
noten = np.array([88, 92, 79, 93, 85, 78, 91, 87, 95, 89])

durchschnitt = np.mean(noten)
standardabweichung = np.std(noten)
min_wert = np.min(noten)
max_wert = np.max(noten)

print('Durchschnitt:', durchschnitt)
print('Standardabweichung:', standardabweichung)
print('Niedrigster Wert:', min_wert)
print('Höchster Wert:', max_wert)

## Matrix-Operationen

### Erstellen von Matrizen

NumPy bietet Funktionen, um spezielle Matrizen zu erstellen:

- **`np.eye(n)`**: Erstellt eine *n x n* Einheitsmatrix
- **`np.random.rand(m, n)`**: Erstellt eine *m x n* Matrix mit zufälligen Werten zwischen 0 und 1

In [31]:
# Einheitsmatrix der Größe 4x4
einheitsmatrix = np.eye(4)
print('Einheitsmatrix:\n', einheitsmatrix)

# Zufällige 3x3 Matrix
random_matrix = np.random.rand(3, 3)
print('Zufalls-Matrix:\n', random_matrix)

Einheitsmatrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Zufalls-Matrix:
 [[0.03065978 0.2410274  0.758296  ]
 [0.47099906 0.33088601 0.5740338 ]
 [0.89333837 0.88160442 0.66779888]]


### Übung: Matrix mit Transponieren und Produkt

Erstelle eine 4x4 Zufallsmatrix (Werte zwischen 0 und 1) mit `np.random.rand`. Transponiere diese Matrix und berechne anschließend das Produkt der Matrix mit ihrer Transponierten.

In [35]:
matrix_4x4 = np.random.randint(1, 10, size=(4, 4))
print('Original 4x4 Matrix:\n', matrix_4x4)

matrix_transponiert = matrix_4x4.T
print('Transponierte Matrix:\n', matrix_transponiert)

produkt = np.dot(matrix_4x4, matrix_transponiert)
print('Produkt der Matrix und ihrer Transponierten:\n', produkt)

produkt = matrix_4x4 @ matrix_transponiert
produkt = matrix_4x4 * matrix_transponiert


Original 4x4 Matrix:
 [[7 4 4 2]
 [7 1 1 9]
 [3 6 8 9]
 [4 5 2 3]]
Transponierte Matrix:
 [[7 7 3 4]
 [4 1 6 5]
 [4 1 8 2]
 [2 9 9 3]]
Produkt der Matrix und ihrer Transponierten:
 [[ 85  75  95  62]
 [ 75 132 116  62]
 [ 95 116 190  85]
 [ 62  62  85  54]]


### Matrixmultiplikation

Führe Matrixmultiplikation entweder mit `np.dot` oder dem `@`-Operator durch.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Mit np.dot
produkt_dot = np.dot(A, B)
print('Matrixmultiplikation mit np.dot:\n', produkt_dot)

# Mit dem @-Operator
produkt_operator = A @ B
print('Matrixmultiplikation mit @-Operator:\n', produkt_operator)

# Mit dem *-Operator ACTUNG: Elementweise Multiplikation ist keine Matrixmultiplikation
produkt_operator = A * B
print('Elementweisemultiplikation mit *-Operator:\n', produkt_operator)

### Übung: Vergleich der Matrixmultiplikation

Erstelle zwei zufällige 3x3 Matrizen (Werte zwischen 0 und 10, z. B. mit `np.random.randint`) und multipliziere sie sowohl mit `np.dot` als auch mit dem `@`-Operator. Vergleiche die Ergebnisse.

In [ ]:
matrix1 = np.random.randint(0, 11, (3, 3))
matrix2 = np.random.randint(0, 11, (3, 3))

print('Matrix 1:\n', matrix1)
print('Matrix 2:\n', matrix2)

produkt1 = np.dot(matrix1, matrix2)
produkt2 = matrix1 @ matrix2

print('Ergebnis mit np.dot:\n', produkt1)
print('Ergebnis mit @-Operator:\n', produkt2)

print('Sind beide Ergebnisse gleich? ', np.allclose(produkt1, produkt2))

In [43]:
import numpy as np

# Rows = items (movies), columns = features [Action, Romance, Comedy]
# Higher number => the item has more of that feature
items = np.array([
    [5, 1, 4],  # Movie 0: mostly action, some comedy
    [1, 5, 2],  # Movie 1: romance-heavy
    [4, 2, 5],  # Movie 2: action + comedy
    [2, 4, 1],  # Movie 3: romance with little comedy
    [3, 1, 5],  # Movie 4: comedy-heavy
], dtype=float)


# Same feature order as columns in `items`: [Action, Romance, Comedy]
# Higher number => the user likes that feature more
user = np.array([5, 0, 4], dtype=float)  # likes action + comedy, not much romance

scores = items @ user 
scores.reshape(-1, 1)

array([[41.],
       [13.],
       [40.],
       [14.],
       [35.]])

In [45]:
import math
a = 0.1 + 0.2
b = 0.3

print(a == b)
print(math.isclose(a, b))

False
True


In [49]:
A = np.array([0.1 + 0.2, 0.5 + 0.3])
B = np.array([0.3, 0.8])

print('A:', A)
print('B:', B)

print('A[0] == B[0]: ', A[0] == B[0])

# print('np.array_equal(A, B): ', np.array_equal(A, B))
print('np.allclose(A, B): ', np.isclose(A, B))
print('np.allclose(A, B): ', np.allclose(A, B))

A: [0.3 0.8]
B: [0.3 0.8]
A[0] == B[0]:  False
np.allclose(A, B):  [ True  True]
np.allclose(A, B):  True


### Transponieren und Umformen

- **Transponieren:** Vertausche Zeilen und Spalten mit `.T`.
- **Umformen:** Ändere die Form eines Arrays mit `np.reshape` (die Gesamtzahl der Elemente muss gleich bleiben).

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Transponiere die Matrix
transponierte_matrix = matrix.T
print('Originale Matrix:\n', matrix)
print('Transponierte Matrix:\n', transponierte_matrix)

# Forme die Matrix um zu einem 3x2 Array
umgeformte_matrix = np.reshape(matrix, (3, 2))
print('Umgeformte Matrix (3x2):\n', umgeformte_matrix)

### Übung: Umformen eines 1D-Arrays

Erstelle ein 1D-Array mit 12 Elementen (z. B. die Zahlen von 0 bis 11). Forme dieses Array zuerst in ein 3x4 Array und dann in ein 2x6 Array. Gib jeweils die Form des Arrays aus.

In [ ]:
array_1d = np.arange(12)
print('1D Array:', array_1d, 'Form:', array_1d.shape)

array_3x4 = np.reshape(array_1d, (3, 4))
print('3x4 Array:\n', array_3x4, 'Form:', array_3x4.shape)

array_2x6 = np.reshape(array_1d, (2, 6))
print('2x6 Array:\n', array_2x6, 'Form:', array_2x6.shape)

## Zusätzliche Übungen

Hier findest du weitere Übungen, um deine Kenntnisse in NumPy zu vertiefen.

## Array-Kombinationen und -Manipulationen

NumPy bietet mehrere Funktionen, um Arrays zu kombinieren und zu manipulieren:

- **`np.concatenate()`**: Verbindet Arrays entlang einer bestehenden Achse
- **`np.vstack()`**: Stapelt Arrays vertikal (zeilenweise)
- **`np.hstack()`**: Stapelt Arrays horizontal (spaltenweise)
- **`np.stack()`**: Stapelt Arrays entlang einer neuen Achse
- **`np.where()`**: Wählt Elemente basierend auf einer Bedingung aus


In [55]:
# Concatenate Arrays
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

print('Array A:', array_a)
print('Array B:', array_b)

# 1D Arrays kombinieren
concatenated = np.concatenate([array_a, array_b])
print('Concatenated 1D Arrays:', concatenated)

Array A: [1 2 3]
Array B: [4 5 6]
Concatenated 1D Arrays: [1 2 3 4 5 6]


In [ ]:
# Stack entlang einer neuen Achse
stack_result = np.stack([array_a, array_b])
print('\nstack Ergebnis:\n', stack_result)


stack Ergebnis:
 [[1 2 3]
 [4 5 6]]


In [52]:
# 2D Arrays vertikal stapeln (vstack)
matrix_1 = np.array([[1, 2], [3, 4]])
matrix_2 = np.array([[5, 6], [7, 8]])
print('Matrix 1:\n', matrix_1)
print('Matrix 2:\n', matrix_2)

vstack_result = np.vstack([matrix_1, matrix_2])
print('\nvstack Ergebnis:\n', vstack_result)

Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]

vstack Ergebnis:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [53]:
# 2D Arrays horizontal stapeln (hstack)
hstack_result = np.hstack([matrix_1, matrix_2])
print('\nhstack Ergebnis:\n', hstack_result)


hstack Ergebnis:
 [[1 2 5 6]
 [3 4 7 8]]


In [57]:
stack_matrix = np.stack([matrix_1, matrix_2])
print('\nstack Matrix Shape:\n', stack_matrix)


stack Matrix Shape:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Übung: Arrays kombinieren

Erstelle zwei 2D-Arrays jeweils mit der Form (2, 3). Kombiniere sie:
1. Vertikal mit `vstack`
2. Horizontal mit `hstack`
3. Gib jeweils die neue Form aus


In [ ]:
# Übung: Arrays kombinieren
arr1 = np.arange(6).reshape(2, 3)
arr2 = np.arange(6, 12).reshape(2, 3)

print('Array 1:\n', arr1)
print('Array 2:\n', arr2)

# Vertikal kombinieren
vstack_result = np.vstack([arr1, arr2])
print('\nvstack Ergebnis (Form: ', vstack_result.shape, '):\n', vstack_result)

# Horizontal kombinieren
hstack_result = np.hstack([arr1, arr2])
print('\nhstack Ergebnis (Form: ', hstack_result.shape, '):\n', hstack_result)


### np.where() – Bedingte Elementauswahl

`np.where()` ist eine mächtige Funktion für bedingte Operationen. Sie kann auf verschiedene Weise verwendet werden:

1. **Bedingter Austausch:** `np.where(condition, if_true, if_false)` – wählt Elemente basierend auf einer Bedingung
2. **Index-Rückgabe:** `np.where(condition)` – gibt die Indizes zurück, an denen die Bedingung erfüllt ist


In [ ]:
my_array = np.array([1, 2, 3, 4, 5, 6])
my_array > 3

array([False, False, False,  True,  True,  True])

In [70]:
# np.where() Beispiele
array_where = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 1. Bedingter Austausch: Ersetze Zahlen > 3 durch 0, sonst durch 100
result_where = np.where(array_where > 3, 0, 100)
print('Array:\n', array_where)
print('np.where(array > 3, 0, 100):\n', result_where)

Array:
 [1 2 3 4 5 6 7 8 9]
np.where(array > 3, 0, 100):
 [100 100 100   0   0   0   0   0   0]


In [71]:
# 2. Indizes finden, wo Bedingung erfüllt ist
indices = np.where(array_where > 5)
print('\nIndizes wo array > 3:\n', indices)
print('Elemente an diesen Indizes:\n', array_where[indices])


Indizes wo array > 3:
 (array([5, 6, 7, 8]),)
Elemente an diesen Indizes:
 [6 7 8 9]


In [73]:
array_where[array_where > 5]

array([6, 7, 8, 9])

In [75]:
# 3. Praktisches Beispiel: Markierung von Noten
noten = np.array([55, 72, 89, 45, 91, 68])
bestanden = np.where(noten >= 70, 'Bestanden', 'Nicht bestanden')
print('\nNoten:', noten)
print('Bestanden/Nicht bestanden:\n', bestanden)


Noten: [55 72 89 45 91 68]
Bestanden/Nicht bestanden:
 ['Nicht bestanden' 'Bestanden' 'Bestanden' 'Nicht bestanden' 'Bestanden'
 'Nicht bestanden']


## Sortieren und Suchen

NumPy bietet Funktionen zum Sortieren und Suchen von Daten:

- **`np.sort()`**: Sortiert ein Array
- **`np.argsort()`**: Gibt die Indizes zurück, die das Array sortieren würden
- **`np.unique()`**: Gibt die eindeutigen Elemente eines Arrays zurück
- **`np.searchsorted()`**: Findet die Position, an der ein Element eingefügt werden sollte


In [107]:
# Sortieren und Suchen
# unsorted_array = np.random.randint(0, 100, size=15).reshape(3, 5)
unsorted_array = np.array([[34, 12, 5, 67, 12],
                           [89, 45, 22, 10, 78],
                           [56, 90, 11, 3, 44]])   
print('Unsortiertes Array:\n', unsorted_array)

Unsortiertes Array:
 [[34 12  5 67 12]
 [89 45 22 10 78]
 [56 90 11  3 44]]


In [108]:
# Sortieren
sorted_array = np.sort(unsorted_array, axis=1)
print('Sortiertes Array:\n', sorted_array)

Sortiertes Array:
 [[ 5 12 12 34 67]
 [10 22 45 78 89]
 [ 3 11 44 56 90]]


In [110]:
# argsort: Gibt die Indizes für das sortierte Array zurück
sort_indices = np.argsort(unsorted_array)
print('Indizes zum Sortieren:', sort_indices)
# print('Überprüfung:', unsorted_array[sort_indices])

Indizes zum Sortieren: [[2 1 4 0 3]
 [3 2 1 4 0]
 [3 2 4 0 1]]


In [111]:
# Unique: Eindeutige Elemente
unique_elements = np.unique(unsorted_array[0, :])
print('\nEindeutige Elemente:', unique_elements)


Eindeutige Elemente: [ 5 12 34 67]


In [84]:
# 2D Array sortieren nach einer Spalte
daten = np.array([[3, 'Alice'], [1, 'Bob'], [2, 'Charlie']], dtype=object)
print('\n2D Array:\n', daten)


2D Array:
 [[3 'Alice']
 [1 'Bob']
 [2 'Charlie']]


In [98]:
# Sortierindex für erste Spalte
sort_idx = np.argsort(daten[:, 0].astype(int))
sorted_daten = daten[sort_idx]
print('Nach erster Spalte sortiert:\n', sorted_daten)

Nach erster Spalte sortiert:
 [[1 'Bob']
 [2 'Charlie']
 [3 'Alice']]


### Übung: Sortieren und Filtern

Gegeben sei ein Array mit den folgenden Werten: `[7, 2, 9, 1, 5, 3, 8]`

1. Sortiere das Array aufsteigend
2. Finde die eindeutigen Elemente
3. Gib die Indizes der sortierten Positionen aus


In [ ]:
# Lösung
array_sort = np.array([7, 2, 9, 1, 5, 3, 8])

print('Original Array:', array_sort)
print('Sortiertes Array:', np.sort(array_sort))
print('Eindeutige Elemente:', np.unique(array_sort))
print('Indizes der sortierten Positionen:', np.argsort(array_sort))


## Fortgeschrittene Array-Slicing-Techniken

Über die grundlegenden Slicing-Techniken hinaus bietet NumPy erweiterte Indizierungsmethoden:

- **Negative Indizierung:** Verwende negative Indizes, um vom Ende des Arrays zu zählen
- **Step-Parameter:** Verwende Schritte zum Auswählen jedes *n*-ten Elements
- **Fancy Indexing:** Verwende Arrays von Indizes zum Auswählen mehrerer Elemente
- **Mehrdimensionales Slicing:** Spezifische Slices für jede Dimension


In [ ]:
# Fortgeschrittene Slicing-Techniken
array_slice = np.arange(10)
print('Array:', array_slice)

# Negative Indizierung
print('Letztes Element (Index -1):', array_slice[-1])
print('Vorletzte 3 Elemente:', array_slice[-3:])

# Step-Parameter (jedes n-te Element)
print('Jeden 2. Eintrag:', array_slice[::2])
print('Rückwärts (jedes 2.):', array_slice[::-2])

# Fancy Indexing: Array von Indizes
indices = np.array([1, 3, 5, 7])
print('Fancy Indexing [1,3,5,7]:', array_slice[indices])

# 2D Fancy Indexing
matrix_2d = np.arange(20).reshape(4, 5)
print('\n2D Matrix:\n', matrix_2d)

# Zeilen 0 und 2 auswählen
selected_rows = matrix_2d[[0, 2], :]
print('Zeilen 0 und 2:\n', selected_rows)

# Spalten 1 und 3 auswählen
selected_cols = matrix_2d[:, [1, 3]]
print('Spalten 1 und 3:\n', selected_cols)


### Übung: Fortgeschrittenes Slicing

Gegeben sei ein 1D-Array mit den Zahlen von 0 bis 19:

1. Wähle alle ungeraden Indizes aus (1, 3, 5, ...)
2. Wähle die letzten 5 Elemente aus
3. Erstelle ein Array mit jedem 3. Element
4. Kehre das Array um (rückwärts)


In [ ]:
# Lösung
array_adv = np.arange(20)

print('Original Array:', array_adv)
print('Ungerade Indizes:', array_adv[1::2])
print('Letzte 5 Elemente:', array_adv[-5:])
print('Jeden 3. Eintrag:', array_adv[::3])
print('Array rückwärts:', array_adv[::-1])


## Datei-Ein-/Ausgabe (File I/O)

NumPy ermöglicht es dir, Arrays in Dateien zu speichern und zu laden. Dies ist wichtig für die Datenkonservierung und den Austausch.

- **`np.save()`**: Speichert ein Array im NumPy-Binärformat (`.npy`)
- **`np.load()`**: Lädt ein Array aus einer `.npy`-Datei
- **`np.savetxt()`**: Speichert ein Array als Textdatei (z. B. CSV)
- **`np.loadtxt()`**: Lädt ein Array aus einer Textdatei


In [ ]:
# File I/O mit NumPy
import os

# Erstelle ein Array
data_to_save = np.array([1.5, 2.3, 3.7, 4.1, 5.9])

# Speichere das Array im Binärformat (.npy)
np.save('/tmp/my_array.npy', data_to_save)
print('Array im Binärformat gespeichert')

# Lade das Array zurück
loaded_array = np.load('/tmp/my_array.npy')
print('Geladenes Array:', loaded_array)

# Speichere als Textdatei (CSV)
np.savetxt('/tmp/my_array.txt', data_to_save, delimiter=',')
print('Array als Textdatei gespeichert')

# Lade Textdatei
loaded_txt = np.loadtxt('/tmp/my_array.txt', delimiter=',')
print('Aus Textdatei geladenes Array:', loaded_txt)

# 2D Array speichern und laden
matrix_data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.savetxt('/tmp/matrix.csv', matrix_data, delimiter=',', fmt='%d')
loaded_matrix = np.loadtxt('/tmp/matrix.csv', delimiter=',')
print('\nGeladene Matrix:\n', loaded_matrix)


### Übung: Speichern und Laden von Arrays

1. Erstelle ein 3x4 Array mit zufälligen Zahlen zwischen 0 und 100
2. Speichere es mit `np.savetxt()` als CSV-Datei
3. Lade die Datei zurück und überprüfe, ob die Daten gleich sind
4. Speichere das gleiche Array mit `np.save()` im Binärformat
5. Lade die binäre Datei und vergleiche


In [ ]:
# Lösung
original_array = np.random.randint(0, 101, (3, 4))
print('Originales Array:\n', original_array)

# Speichere als CSV
np.savetxt('/tmp/array_csv.txt', original_array, delimiter=',', fmt='%d')
csv_loaded = np.loadtxt('/tmp/array_csv.txt', delimiter=',')
print('\nAus CSV geladen:\n', csv_loaded)
print('CSV-Daten gleich? ', np.array_equal(original_array.astype(float), csv_loaded))

# Speichere als Binary
np.save('/tmp/array_bin.npy', original_array)
binary_loaded = np.load('/tmp/array_bin.npy')
print('\nAus Binärformat geladen:\n', binary_loaded)
print('Binär-Daten gleich? ', np.array_equal(original_array, binary_loaded))


## Lineare Algebra mit NumPy (`np.linalg`)

Das Submodul `numpy.linalg` bietet Funktionen für Operationen der linearen Algebra:

- **`np.linalg.det()`**: Berechnet die Determinante einer Matrix
- **`np.linalg.inv()`**: Berechnet die Inverse einer Matrix
- **`np.linalg.solve()`**: Löst ein lineares Gleichungssystem
- **`np.linalg.eig()`**: Berechnet Eigenwerte und Eigenvektoren
- **`np.linalg.norm()`**: Berechnet die Norm eines Vektors oder einer Matrix
- **`np.linalg.rank()`**: Bestimmt den Rang einer Matrix


In [ ]:
# Lineare Algebra Beispiele
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

print('Matrix A:\n', A)
print('Vektor b:', b)

# Determinante
det_A = np.linalg.det(A)
print('\nDeterminante von A:', det_A)

# Rang der Matrix
rank_A = np.linalg.matrix_rank(A)
print('Rang von A:', rank_A)

# Norm eines Vektors
norm_b = np.linalg.norm(b)
print('Norm von b:', norm_b)

# Lineares Gleichungssystem lösen: A*x = b
if det_A != 0:
    x = np.linalg.solve(A, b)
    print('\nLösung von A*x = b:', x)
    print('Überprüfung (A @ x):', A @ x)

# Eigenwerte und Eigenvektoren
eigenvalues, eigenvectors = np.linalg.eig(A)
print('\nEigenwerte:', eigenvalues)
print('Eigenvektoren:\n', eigenvectors)


### Übung: Lineare Gleichungssysteme lösen

Löse das folgende lineare Gleichungssystem mit NumPy:

```
2x + 3y = 8
4x - y = 5
```

1. Definiere die Koeffizientenmatrix `A` und den Vektor `b`
2. Verwende `np.linalg.solve()`, um x und y zu finden
3. Überprüfe deine Lösung, indem du `A @ [x, y]` berechnest


In [ ]:
# Lösung
# 2x + 3y = 8
# 4x - y = 5

A_eq = np.array([[2, 3], [4, -1]])
b_eq = np.array([8, 5])

print('Koeffizientenmatrix A:\n', A_eq)
print('Vektor b:', b_eq)

# Löse das Gleichungssystem
solution = np.linalg.solve(A_eq, b_eq)
x, y = solution
print('\nLösung: x =', x, ', y =', y)

# Überprüfung
verification = A_eq @ solution
print('Überprüfung (A @ [x, y]):', verification)
print('Sollte gleich b sein:', b_eq)


## Zufallszahlengenerierung (Erweiterte Konzepte)

Das Submodul `numpy.random` bietet verschiedene Funktionen zur Generierung von Zufallszahlen aus unterschiedlichen Verteilungen:

- **`np.random.randn()`**: Normalverteilung (Gaußverteilung)
- **`np.random.randint()`**: Zufällige Ganzzahlen
- **`np.random.uniform()`**: Gleichverteilung
- **`np.random.exponential()`**: Exponentialverteilung
- **`np.random.choice()`**: Zufällige Auswahl aus einem Array
- **`np.random.shuffle()`**: Mischt ein Array
- **`np.random.seed()`**: Setzt einen Seed für Reproduzierbarkeit


In [ ]:
# Zufallszahlengenerierung - Erweiterte Beispiele

# Normalverteilung
normal_data = np.random.randn(5)
print('Normalverteilung:', normal_data)

# Gleichverteilung (Uniform)
uniform_data = np.random.uniform(0, 10, 5)
print('Gleichverteilung [0, 10]:', uniform_data)

# Exponentialverteilung
exponential_data = np.random.exponential(scale=2, size=5)
print('Exponentialverteilung:', exponential_data)

# Zufällige Auswahl aus einem Array (mit/ohne Zurücklegen)
choices = np.random.choice([1, 2, 3, 4, 5], size=10, replace=True)
print('\nZufällige Auswahl (mit Zurücklegen):', choices)

choices_no_replace = np.random.choice([1, 2, 3, 4, 5], size=5, replace=False)
print('Zufällige Auswahl (ohne Zurücklegen):', choices_no_replace)

# Shuffle
array_to_shuffle = np.arange(10)
np.random.shuffle(array_to_shuffle)
print('\nGemischtes Array:', array_to_shuffle)

# Reproduzierbarkeit mit Seed
np.random.seed(42)
reproducible_1 = np.random.randn(3)
print('\nMit Seed 42 (1. Aufruf):', reproducible_1)

np.random.seed(42)
reproducible_2 = np.random.randn(3)
print('Mit Seed 42 (2. Aufruf):', reproducible_2)
print('Sind sie gleich? ', np.array_equal(reproducible_1, reproducible_2))


### Übung: Simulation eines Würfelspiels

Simuliere 10.000 Würfelwürfe mit `np.random.choice()`:

1. Verwende `np.random.choice()`, um 10.000 zufällige Ergebnisse zwischen 1 und 6 zu generieren
2. Berechne, wie oft jede Zahl auftrat
3. Berechne die durchschnittliche Häufigkeit (sollte bei einem fairen Würfel etwa 1667 sein)
4. Berechne die Standardabweichung


In [ ]:
# Lösung: Würfelsimulation
np.random.seed(42)  # Für Reproduzierbarkeit
dice_rolls = np.random.choice([1, 2, 3, 4, 5, 6], size=10000)

print('Würfelwürfe durchgeführt: 10.000')

# Zähle die Häufigkeiten
unique_values, counts = np.unique(dice_rolls, return_counts=True)
print('\nHäufigkeit jeder Zahl:')
for value, count in zip(unique_values, counts):
    print(f'  Würfel {value}: {count} mal')

# Durchschnittliche Häufigkeit
avg_frequency = np.mean(counts)
print(f'\nDurchschnittliche Häufigkeit: {avg_frequency:.2f}')
print(f'Erwartete Häufigkeit (fair): {10000/6:.2f}')

# Standardabweichung
std_frequency = np.std(counts)
print(f'Standardabweichung der Häufigkeiten: {std_frequency:.2f}')


## Performance-Optimierung und Vergleich

Eine der größten Stärken von NumPy ist die Geschwindigkeit. Lassen Sie uns die Performance-Unterschiede zwischen Python-Schleifen und vektorisierten NumPy-Operationen untersuchen, sowie verschiedene Optimierungstechniken.


In [2]:
# Performance-Vergleich: Python-Schleife vs. NumPy

import time
import numpy as np
# Erstelle große Listen und Arrays
n = 1_000_000
list_a = list(range(n))
list_b = list(range(n, 2*n))
array_a = np.arange(n)
array_b = np.arange(n, 2*n)

# 1. Python-Schleife: Addition zweier Listen
start = time.time()
result_list = [list_a[i] + list_b[i] for i in range(n)]
time_list = time.time() - start
print(f'Python-Schleife (Addition): {time_list:.4f} Sekunden')

# 2. NumPy vektorisiert: Addition zweier Arrays
start = time.time()
result_array = array_a + array_b
time_numpy = time.time() - start
print(f'NumPy vektorisiert: {time_numpy:.4f} Sekunden')

print(f'NumPy ist {time_list / time_numpy:.1f}x schneller')

# 3. Speicherverbrauch
import sys
size_list = sys.getsizeof(list_a)
size_array = array_a.nbytes
print(f'\nSpeicher (Python-Liste): {size_list / 1024 / 1024:.2f} MB')
print(f'Speicher (NumPy-Array): {size_array / 1024 / 1024:.2f} MB')
print(f'NumPy spart {size_list / size_array:.1f}x Speicher')


Python-Schleife (Addition): 0.2886 Sekunden
NumPy vektorisiert: 0.0081 Sekunden
NumPy ist 35.7x schneller

Speicher (Python-Liste): 7.63 MB
Speicher (NumPy-Array): 7.63 MB
NumPy spart 1.0x Speicher


### Performance-Tipps für NumPy

1. **Vektorisierung verwenden:** Verwende NumPy-Operationen statt Python-Schleifen
2. **In-Place-Operationen:** Verwende `+=`, `-=` etc., um Speicher zu sparen
3. **Richtige Datentypen:** Verwende effiziente Datentypen (z. B. `int32` statt `int64` wenn möglich)
4. **Broadcasting nutzen:** Anstatt Arrays zu replizieren
5. **Kontiguität prüfen:** Sorge für effiziente Speicherlayouts mit `np.ascontiguousarray()`


In [ ]:
# In-Place Operationen Beispiel
import time

n = 10_000_000
array = np.arange(n, dtype=float)

# Normale Operation (erzeugt ein neues Array)
start = time.time()
for _ in range(100):
    result = array + 1
time_normal = time.time() - start
print(f'Normale Addition (100x): {time_normal:.4f} Sekunden')

# In-Place Operation (modifiziert das Array)
array = np.arange(n, dtype=float)
start = time.time()
for _ in range(100):
    array += 1  # In-Place
time_inplace = time.time() - start
print(f'In-Place Addition (100x): {time_inplace:.4f} Sekunden')

print(f'In-Place ist {time_normal / time_inplace:.1f}x schneller')

# Datentypen Vergleich
array_f64 = np.arange(1_000_000, dtype=np.float64)
array_f32 = np.arange(1_000_000, dtype=np.float32)

start = time.time()
for _ in range(1000):
    result = array_f64 * 2
time_f64 = time.time() - start

start = time.time()
for _ in range(1000):
    result = array_f32 * 2
time_f32 = time.time() - start

print(f'\nfloat64 (1000x): {time_f64:.4f} Sekunden')
print(f'float32 (1000x): {time_f32:.4f} Sekunden')


### Übung: Performance-Vergleich schreiben

Vergleiche die Performance von:

1. **Skalarprodukt mit Python-Schleife:** Berechne das Skalarprodukt zweier Vektoren mit einer Schleife
2. **Skalarprodukt mit NumPy:** Berechne das Skalarprodukt mit `np.dot()`
3. Messe die Zeit für jeweils 10.000 Iterationen bei Vektoren der Länge 1000
4. Berechne den Speed-Up-Faktor


In [ ]:
# Lösung: Skalarprodukt-Performance

def scalar_product_python(a, b):
    """Skalarprodukt mit Python-Schleife"""
    result = 0
    for i in range(len(a)):
        result += a[i] * b[i]
    return result

# Erstelle große Vektoren
vec_len = 1000
vec_a_list = list(range(vec_len))
vec_b_list = list(range(vec_len, 2 * vec_len))
vec_a_numpy = np.arange(vec_len)
vec_b_numpy = np.arange(vec_len, 2 * vec_len)

# Python-Schleife
start = time.time()
for _ in range(10000):
    result_py = scalar_product_python(vec_a_list, vec_b_list)
time_python = time.time() - start

# NumPy
start = time.time()
for _ in range(10000):
    result_np = np.dot(vec_a_numpy, vec_b_numpy)
time_numpy = time.time() - start

print(f'Python-Schleife (10.000x): {time_python:.4f} Sekunden')
print(f'NumPy (10.000x): {time_numpy:.4f} Sekunden')
print(f'Speed-Up-Faktor: {time_python / time_numpy:.0f}x')


### Übung: Boolean Indexing und Filtern

Erstelle ein 1D-Array mit 20 zufälligen Ganzzahlen zwischen 0 und 100. Verwende Boolean Indexing, um alle Zahlen größer als 50 auszuwählen und auszugeben. Ersetze dann alle Zahlen, die kleiner oder gleich 50 sind, durch 0 und gib das modifizierte Array aus.

In [ ]:
# Übung: Boolean Indexing und Filtern
array_5 = np.random.randint(0, 101, 20)
print('Originales Array:')
print(array_5)

zahlen_ueber_50 = array_5 > 50
print(zahlen_ueber_50)

# Auswahl der Zahlen größer als 50
zahlen_groesser_50 = array_5[zahlen_ueber_50]
print('\nZahlen größer als 50:')
print(zahlen_groesser_50)

# Ersetze Zahlen <= 50 durch 0
array_5[array_5 <= 50] = 0
print('\nModifiziertes Array (alle Zahlen <= 50 durch 0 ersetzt):')
print(array_5)

### Übung: Umformen und Flattening

Erstelle ein 1D-Array mit den Zahlen von 1 bis 24. Forme das Array in ein 2D-Array der Form **(4, 6)** um. Wandle das 2D-Array dann wieder in ein 1D-Array um (flatten) und berechne die Transponierte des 2D-Arrays.

In [ ]:
# Übung: Umformen und Flattening
array_6 = np.arange(1, 25)
print('Originales 1D-Array:')
print(array_6)

array_2d = array_6.reshape((4, 6))
print('\n2D-Array (4x6):')
print(array_2d)

array_flatten = array_2d.flatten()
print('\nZurück in ein 1D-Array (flatten):')
print(array_flatten)

array_transpose = array_2d.T
print('\nTransponiertes 2D-Array:')
print(array_transpose)

### Übung: Matrix Determinante und Inverse

Erstelle eine 3x3 Matrix, zum Beispiel `[[4, 2, 1], [0, 3, -1], [2, 1, 3]]`. Berechne die Determinante dieser Matrix mit `np.linalg.det`. Falls die Determinante ungleich Null ist, berechne die Inverse der Matrix mit `np.linalg.inv` und verifiziere das Ergebnis, indem du die Matrix mit ihrer Inversen multiplizierst (das Ergebnis sollte die Einheitsmatrix sein).

In [ ]:
# Übung: Matrix Determinante und Inverse
matrix_7 = np.array([[4, 2, 1], [0, 3, -1], [2, 1, 3]])
print('Matrix:')
print(matrix_7)

determinante = np.linalg.det(matrix_7)
print('\nDeterminante:', determinante)

if np.abs(determinante) > 1e-6:
    matrix_inv = np.linalg.inv(matrix_7)
    print('\nInverse Matrix:')
    print(matrix_inv)
    identitaet = matrix_7 @ matrix_inv
    print('\nMatrix * Inverse (sollte die Einheitsmatrix sein):')
    print(identitaet)
else:
    print('Die Matrix ist singulär und hat keine Inverse.')

### Übung: Zufällige Stichprobe und Statistik

Erstelle ein 1D-Array mit 1000 zufälligen Zahlen aus einer Normalverteilung mithilfe von `np.random.randn()`. Berechne den Mittelwert, Median, die Varianz und die Standardabweichung des Arrays. Zeichne anschließend ein Histogramm, um die Verteilung zu visualisieren.

In [ ]:
# Übung: Zufällige Stichprobe und Statistik
array_8 = np.random.randn(1000)
mean_8 = np.mean(array_8)
median_8 = np.median(array_8)
varianz_8 = np.var(array_8)
std_8 = np.std(array_8)

array_9 = array_8 * 2 + 5

print('Mittelwert:', mean_8)
print('Median:', median_8)
print('Varianz:', varianz_8)
print('Standardabweichung:', std_8)

# Histogramm plotten (falls matplotlib verfügbar ist)
import matplotlib.pyplot as plt
plt.hist(array_8, bins=30, edgecolor='black')
plt.hist(array_9, bins=30, edgecolor='black')
plt.title('Histogramm der Normalverteilung')
plt.xlabel('Wert')
plt.ylabel('Häufigkeit')
plt.show()


In [16]:
import numpy as np

my_first_array=np.array([1,2,3,4])

my_second_array=np.array([[20.5,14.20],[30.8,80.41]])

print(my_first_array)
print(my_second_array)

my_first_array.ndim
#my_second_array.ndim

print(my_second_array.shape)

print(my_first_array.dtype)


[1 2 3 4]
[[20.5  14.2 ]
 [30.8  80.41]]
(2, 2)
int64


## Zusammenfassung

In diesem Notebook haben wir gelernt:

- Die Bedeutung und Vorteile von NumPy
- Wie man NumPy installiert und importiert
- Verschiedene Möglichkeiten, Arrays zu erstellen und deren Eigenschaften zu inspizieren
- Array-Operationen wie Indexierung, Slicing, elementweise arithmetische Operationen und Broadcasting
- Matrixoperationen wie Multiplikation, Transponieren und Umformen
- Praktische Übungen zur Anwendung dieser Konzepte

Diese Grundlagen sind hilfreich, wenn wir in der nächsten Lektion fortgeschrittene Datenmanipulationsbibliotheken wie **Pandas** erkunden.

### Nächste Schritte

In der nächsten Lektion werden wir uns mit **Pandas** beschäftigen – einer leistungsstarken Bibliothek zur Datenmanipulation und -analyse in Python. Bleib dran!

## Weiterführende Ressourcen zu NumPy

NumPy bietet eine Vielzahl von Funktionen für numerische Berechnungen, die weit über das hinausgehen, was wir in dieser Einführung behandelt haben. 
Es ist wichtig, regelmäßig die **offizielle Dokumentation** und verschiedene **Tutorials** zu lesen, um NumPy effektiv zu nutzen.

### Offizielle Dokumentation und Einsteigerleitfäden:
- [NumPy Quickstart Tutorial](https://numpy.org/doc/stable/user/quickstart.html)
- [NumPy Leitfaden für absolute Anfänger](https://numpy.org/doc/stable/user/absolute_beginners.html)

### Illustrierte NumPy-Tutorials:
- [NumPy Illustrated: The Visual Guide to NumPy](https://medium.com/better-programming/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d)
- [A Visual Intro to NumPy and Data Representation](https://jalammar.github.io/visual-numpy/)

Diese Ressourcen enthalten detaillierte Erklärungen und **grafische Darstellungen**, die helfen, NumPy besser zu verstehen. Sie eignen sich hervorragend für das eigenständige Lernen und zur Vertiefung der Kenntnisse nach diesem Kurs.